name: PointUMaze
path_to_expert: /home/nazar/projects/CDIL/prep_data/pointumaze/pointumaze/expert_source/trained_expert.npy
path_to_random_expert: /home/nazar/projects/CDIL/prep_data/pointumaze/pointumaze/rand_source/random_policy.npy
path_to_random_target: /home/nazar/projects/CDIL/prep_data/pointumaze/pointumaze/rand_target/random_policy.npy
