# @package _global_

defaults:
  - _self_
  - env: pointantumaze #pointantumaze # pointumaze
  - algo: sac
  - logger: wandb

seed: 42
max_steps: 1_000
log_interval: 10_000
video_log_interval: 50
eval_episodes: 10
eval_interval: 1_000
save_expert_episodes: 20